name: Buildm

on:
  push

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019
    
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        arch:
          - win64
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build
        continue-on-error: true
        run: |
          git submodule update --init --recursive --depth 1 --recommend-shallow
          cd LibRaw
          msbuild.exe /p:DefineConstants="USE_X3FTOOLS USE_6BY9RPI USE_OLD_VIDEOCAMS" /p:Platform=x64 /p:configuration="Release" LibRaw.sln /t:libraw
      - name: moving
        run: |
          mkdir upload
          mv LibRaw/buildfiles/release-x86_64/libraw.dll upload
          mv LibRaw/buildfiles/release-x86_64/libraw.lib upload
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: releaselibraw64
          path: upload
      # ...
